import { useState } from 'react'
import { AdminDataProvider, useAdminData } from './AdminDataContext.jsx'
import { ApprovalQueue } from './ApprovalQueue.jsx'

const statusLabels = { approved: 'Approved', pending: 'Pending', rejected: 'Rejected', suspended: 'Suspended', completed: 'Completed', cancelled: 'Cancelled' }
function StatusBadge({ status }) { return <span className={`admin-status status-${status}`}>{statusLabels[status] || status}</span> }
function PageHeading({ eyebrow, title, description, action }) { return <div className="admin-page-heading"><div><p className="admin-kicker">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{action}</div> }

function Sidebar({ page, navigate }) {
  return <aside className="admin-sidebar"><div className="admin-brand"><span className="admin-brand-mark">B</span><span><strong>Booking</strong><small>Operations</small></span></div><div className="admin-profile"><div className="admin-avatar">AM</div><div><strong>Admin manager</strong><small>System administrator</small></div></div><p className="admin-nav-label">Workspace</p><nav className="admin-nav"><button className={page === 'overview' ? 'active' : ''} onClick={() => navigate('overview')}>▦ <span>Overview</span></button><button className={page === 'vendors' ? 'active' : ''} onClick={() => navigate('vendors')}>♧ <span>Vendors</span><b>4</b></button><button className={page === 'bookings' ? 'active' : ''} onClick={() => navigate('bookings')}>▤ <span>Bookings</span><b>12</b></button></nav><div className="admin-sidebar-footer"><span className="status-dot" />All systems operational<button onClick={() => { window.location.hash = '#home' }}>← Back to site</button></div></aside>
}

function Overview({ navigate }) {
  const { vendors, bookings } = useAdminData()
  return <><PageHeading eyebrow="Saturday, September 19, 2026" title="Good morning, Admin" description="Here is what is happening across your marketplace today." /><section className="admin-stat-grid"><article><span className="stat-icon blue">♧</span><p>Active vendors</p><strong>{vendors.filter((vendor) => vendor.status === 'approved').length}</strong><small><em>+2</em> this month</small></article><article><span className="stat-icon green">▤</span><p>Total bookings</p><strong>{bookings.length}</strong><small><em>+18.4%</em> vs last month</small></article><article><span className="stat-icon amber">◷</span><p>Needs review</p><strong>{vendors.filter((vendor) => vendor.status === 'pending').length + bookings.filter((booking) => booking.status === 'pending').length}</strong><small>Requires your attention</small></article><article><span className="stat-icon coral">$</span><p>Gross volume</p><strong>$12.8k</strong><small><em>+9.2%</em> this month</small></article></section><section className="admin-overview-grid"><article className="admin-panel"><div className="panel-heading"><div><p className="admin-kicker">Latest activity</p><h2>Recent bookings</h2></div><button className="text-button" onClick={() => navigate('bookings')}>View all →</button></div><div className="activity-list">{bookings.slice(0, 3).map((booking) => <div className="activity-row" key={booking.id}><div className="activity-avatar">{booking.guest.split(' ').map((name) => name[0]).join('')}</div><div><strong>{booking.guest}</strong><p>{booking.service}</p></div><StatusBadge status={booking.status} /><span>{booking.amount}</span></div>)}</div></article><article className="admin-panel attention-panel"><p className="admin-kicker">Your attention</p><h2>Pending approvals</h2><p className="panel-description">Keep the marketplace fresh by reviewing new vendor applications.</p><div className="attention-number">{vendors.filter((vendor) => vendor.status === 'pending').length}<span>vendor applications</span></div><button className="primary-button" onClick={() => navigate('vendors')}>Review vendors <span>→</span></button></article></section></>
}

function VendorsPage() {
  const { vendors, setVendorStatus, deleteVendor } = useAdminData()
  const [query, setQuery] = useState('')
  const filtered = vendors.filter((vendor) => `${vendor.name} ${vendor.type} ${vendor.location}`.toLowerCase().includes(query.toLowerCase()))
  return <><PageHeading eyebrow="Marketplace management" title="Vendors" description="Review, approve, and manage every partner on your platform." action={<button className="primary-button">+ Add vendor</button>} /><div className="admin-toolbar"><div className="search-box">⌕<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search vendors" /></div><select><option>All statuses</option><option>Pending</option><option>Approved</option></select><select><option>All types</option><option>Hotel</option><option>Airline</option><option>Tour operator</option></select></div><section className="admin-panel table-panel"><div className="table-meta"><strong>{filtered.length} vendors</strong><span>Updated just now</span></div><div className="admin-table-wrap"><table><thead><tr><th>Vendor</th><th>Type</th><th>Location</th><th>Specialties</th><th>Status</th><th>Joined</th><th /></tr></thead><tbody>{filtered.map((vendor) => <tr key={vendor.id}><td><div className="table-person"><div className="vendor-avatar">{vendor.name[0]}</div><div><strong>{vendor.name}</strong><small>{vendor.email}</small></div></div></td><td>{vendor.type}</td><td>{vendor.location}</td><td><div className="tag-list">{vendor.sectors.map((sector) => <span key={sector}>{sector}</span>)}</div></td><td><StatusBadge status={vendor.status} /></td><td>{vendor.joined}</td><td><select className="row-action" value={vendor.status} onChange={(event) => setVendorStatus(vendor.id, event.target.value)} aria-label={`Change status for ${vendor.name}`}><option value="approved">Approve</option><option value="pending">Review</option><option value="suspended">Suspend</option><option value="rejected">Reject</option></select><button className="delete-button" onClick={() => deleteVendor(vendor.id)} aria-label={`Delete ${vendor.name}`}>×</button></td></tr>)}</tbody></table></div></section></>
}

function BookingsPage() {
  const { bookings, setBookingStatus } = useAdminData()
  const [query, setQuery] = useState('')
  const filtered = bookings.filter((booking) => `${booking.reference} ${booking.guest} ${booking.service} ${booking.vendor}`.toLowerCase().includes(query.toLowerCase()))
  return <><PageHeading eyebrow="Revenue and reservations" title="Bookings" description="Track every reservation and keep guests and vendors moving." /><div className="admin-toolbar"><div className="search-box">⌕<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by guest, reference, or vendor" /></div><select><option>All statuses</option><option>Pending</option><option>Approved</option><option>Completed</option></select><button className="filter-button">≡ Filters</button></div><section className="admin-panel table-panel"><div className="table-meta"><strong>{filtered.length} bookings</strong><span>September 2026</span></div><div className="admin-table-wrap"><table><thead><tr><th>Reference</th><th>Guest</th><th>Service / vendor</th><th>Date</th><th>Amount</th><th>Status</th><th /></tr></thead><tbody>{filtered.map((booking) => <tr key={booking.id}><td><strong className="reference">{booking.reference}</strong></td><td>{booking.guest}</td><td><strong>{booking.service}</strong><small className="cell-subtext">{booking.vendor}</small></td><td>{booking.date}</td><td><strong>{booking.amount}</strong></td><td><StatusBadge status={booking.status} /></td><td><select className="row-action" value={booking.status} onChange={(event) => setBookingStatus(booking.id, event.target.value)} aria-label={`Change status for ${booking.reference}`}><option value="approved">Approve</option><option value="pending">Reopen</option><option value="completed">Complete</option><option value="rejected">Reject</option><option value="cancelled">Cancel</option></select></td></tr>)}</tbody></table></div></section></>
}

function DashboardContent() {
  const [page, setPage] = useState(window.location.hash === '#admin/vendors' ? 'vendors' : window.location.hash === '#admin/bookings' ? 'bookings' : 'overview')
  const navigate = (nextPage) => { setPage(nextPage); window.location.hash = nextPage === 'overview' ? '#admin' : `#admin/${nextPage}` }
  const { notice } = useAdminData()
  return <div className="admin-shell"><Sidebar page={page} navigate={navigate} /><main className="admin-main"><header className="admin-topbar"><div className="admin-breadcrumb">Admin <span>/</span> {page[0].toUpperCase() + page.slice(1)}</div><div className="admin-top-actions"><button aria-label="Notifications" className="notification-button">♢<i /></button><div className="admin-user">AM <span>Admin manager</span>⌄</div></div></header><div className="admin-content">{page === 'overview' && <><Overview navigate={navigate} /><div className="admin-queue-row"><ApprovalQueue navigate={navigate} /></div></>}{page === 'vendors' && <VendorsPage />}{page === 'bookings' && <BookingsPage />}</div>{notice && <div className="admin-toast">✓ {notice}</div>}</main></div>
}

export default function AdminDashboard() { return <AdminDataProvider><DashboardContent /></AdminDataProvider> }